@baseUrl = https://localhost:7003
@deliveryId = 63bb3bfb-b0a0-4bce-aaa8-b488e04e7739
@routeId = d3ee9d28-461c-4503-9ae1-10730c6c71e1
@deliveryStatus = Delivered

### Get All Deliveries
GET {{baseUrl}}/api/v1/DeliveryLookup
Accept: application/json

### Get Delivery By ID
GET {{baseUrl}}/api/v1/DeliveryLookup/byId/{{deliveryId}}
Accept: application/json

### Get Deliveries By Status
GET {{baseUrl}}/api/v1/DeliveryLookup/byStatus/{{deliveryStatus}}
Accept: application/json

### Get Deliveries By Route ID
GET {{baseUrl}}/api/v1/DeliveryLookup/byRoute/{{routeId}}
Accept: application/json

### Get All Delivery Statuses
GET {{baseUrl}}/api/v1/DeliveryLookup/statuses
Accept: application/json

### Get Incidents By Delivery ID
GET {{baseUrl}}/api/v1/IncidentLookup/byDelivery/{{deliveryId}}
Accept: application/json

### Get All Unresolved Incidents
GET {{baseUrl}}/api/v1/IncidentLookup/unresolved
Accept: application/json
