@host = https://localhost:7002
@hostHttp = http://localhost:5002
@driverId = 169d6944-f716-4337-94de-cacf16250f11
@vehicleId = 5a1b2c3d-4e5f-6789-0abc-def123456700

### Get all drivers
GET {{host}}/api/v1/DriverLookup

### Get driver by ID
GET {{host}}/api/v1/DriverLookup/byId/{{driverId}}

### Get all vehicles
GET {{host}}/api/v1/VehicleLookup

### Get vehicle by ID
GET {{host}}/api/v1/VehicleLookup/byId/{{vehicleId}}

### Get vehicles by driver
GET {{host}}/api/v1/VehicleLookup/byDriver/{{driverId}}

### Get drivers by status
GET {{host}}/api/v1/DriverLookup/byStatus/Available

### Get vehicles by status
GET {{host}}/api/v1/VehicleLookup/byStatus/Available

### Get all driver statuses
GET {{host}}/api/v1/DriverLookup/statuses

### Get all vehicle statuses
GET {{host}}/api/v1/VehicleLookup/statuses
